interface CacheCreationUsage {
  ephemeral_1h_input_tokens?: number;
  ephemeral_5m_input_tokens?: number;
}

export interface TokenUsage {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_input_tokens?: number;
  cache_creation_input_tokens?: number;
  cache_creation?: CacheCreationUsage;
}

interface ContextTokenState {
  inputTokens?: number;
  outputTokens?: number;
  contextInputTokens?: number;
  contextOutputTokens?: number;
}

function tokenCount(value: number | undefined): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) return 0;
  return value;
}

/** Tokens occupying the context before the current assistant response. */
export function getContextInputTokens(usage: TokenUsage | undefined): number {
  if (!usage) return 0;
  const cacheCreationTokens = tokenCount(usage.cache_creation_input_tokens)
    || (
      tokenCount(usage.cache_creation?.ephemeral_1h_input_tokens)
      + tokenCount(usage.cache_creation?.ephemeral_5m_input_tokens)
    );
  return tokenCount(usage.input_tokens)
    + tokenCount(usage.cache_read_input_tokens)
    + cacheCreationTokens;
}

/** Output tokens generated by the current model call. */
export function getContextOutputTokens(usage: TokenUsage | undefined): number {
  return tokenCount(usage?.output_tokens);
}

/** Ignore synthetic/control records whose usage object contains no real tokens. */
export function hasMeaningfulContextUsage(usage: TokenUsage | undefined): boolean {
  return getContextInputTokens(usage) + getContextOutputTokens(usage) > 0;
}

/** Prefer the stable context snapshot over per-turn counters that reset on send. */
export function getContextUsedTokens(state: ContextTokenState): number {
  return tokenCount(state.contextInputTokens ?? state.inputTokens)
    + tokenCount(state.contextOutputTokens ?? state.outputTokens);
}
